name: Diff WebKit Branches

on:
  workflow_dispatch:
    inputs:
      from_branch:
        description: "Branch to diff from (e.g. safari-613-branch)"
        required: true
        default: "safari-613-branch"
      to_branch:
        description: "Branch to diff to (e.g. safari-614-branch)"
        required: true
        default: "safari-614-branch"

jobs:
  diff:
    runs-on: ubuntu-latest
    steps:
      - name: Clone WebKit repository
        run: |
          git clone https://github.com/WebKit/WebKit.git webkit
          cd webkit
          git fetch origin +refs/heads/${{ github.event.inputs.from_branch }}:refs/remotes/origin/${{ github.event.inputs.from_branch }}
          git fetch origin +refs/heads/${{ github.event.inputs.to_branch }}:refs/remotes/origin/${{ github.event.inputs.to_branch }}

      - name: Generate Filtered Diff
        run: |
          cd webkit
          git diff origin/${{ github.event.inputs.from_branch }}..origin/${{ github.event.inputs.to_branch }} \
            -- Source/JavaScriptCore \
               Source/WebCore \
               Source/WebKit \
          > ../filtered_diff.patch

          echo "✅ Diff saved to filtered_diff.patch"

      - name: Upload Diff Artifact
        uses: actions/upload-artifact@v4
        with:
          name: filtered-diff
          path: filtered_diff.patch