name: Diff WebKit Branches

on:
  workflow_dispatch:
    inputs:
      from_branch:
        description: "Branch to diff from (e.g. safari-613-branch)"
        required: true
        default: "safari-613-branch"
      to_branch:
        description: "Branch to diff to (e.g. safari-614-branch)"
        required: true
        default: "safari-614-branch"

jobs:
  diff:
    runs-on: ubuntu-latest
    steps:
      - name: Clone WebKit repository
        run: |
          git clone https://github.com/WebKit/WebKit.git webkit
          cd webkit
          git fetch origin +refs/heads/${{ github.event.inputs.from_branch }}:refs/remotes/origin/${{ github.event.inputs.from_branch }}
          git fetch origin +refs/heads/${{ github.event.inputs.to_branch }}:refs/remotes/origin/${{ github.event.inputs.to_branch }}

      - name: Generate Diff + Commits (classified + suspicious markers)
        run: |
          cd webkit

          # استخراج commits
          git log origin/${{ github.event.inputs.from_branch }}..origin/${{ github.event.inputs.to_branch }} \
            --pretty=format:'%H|%h|%s' > ../commits_raw.txt

          sec_count=0; perf_count=0; ref_count=0; total=0

          {
            echo "<html><head><style>"
            echo "body { font-family: Arial, sans-serif; background: #f4f6f8; padding: 30px; color: #333; }"
            echo "h1 { background: #2d3748; color: white; padding: 12px; border-radius: 8px; }"
            echo "nav { margin: 20px 0; }"
            echo "nav a { margin-right: 15px; text-decoration: none; color: #2d3748; font-weight: bold; }"
            echo "nav a:hover { text-decoration: underline; }"
            echo "h2 { margin-top: 30px; border-bottom: 2px solid #ddd; padding-bottom: 6px; color: #2d3748; }"
            echo "ul { list-style: none; padding: 0; }"
            echo "li { margin: 8px 0; padding: 6px; border-radius: 6px; }"
            echo "li a { text-decoration: none; color: inherit; }"
            echo ".security { background: #ffe5e5; border-left: 4px solid red; }"
            echo ".perf { background: #e5ffe5; border-left: 4px solid green; }"
            echo ".refactor { background: #e5f0ff; border-left: 4px solid blue; }"
            echo ".other { background: #f1f1f1; border-left: 4px solid gray; }"
            echo ".danger { background: #fff3cd; font-weight: bold; color: #b45309; display: block; }"
            echo "pre { background: #1e293b; color: #e2e8f0; padding: 15px; border-radius: 8px; overflow-x: auto; }"
            echo ".back { margin-top: 15px; display: inline-block; background: #2d3748; color: white; padding: 6px 12px; border-radius: 6px; text-decoration: none; }"
            echo ".back:hover { background: #4a5568; }"
            echo "</style></head><body>"

            echo "<h1 id=\"top\">WebKit Branch Diff Report</h1>"
            echo "<p>From <b>${{ github.event.inputs.from_branch }}</b> → To <b>${{ github.event.inputs.to_branch }}</b></p>"

            # navigation links
            echo "<nav>"
            echo "<a href=\"#commits\">Commits</a>"
            echo "<a href=\"#summary\">Summary</a>"
            echo "<a href=\"#diff\">Diff</a>"
            echo "</nav>"

            # commits list
            echo "<h2 id=\"commits\">Commits</h2><ul>"
            while IFS="|" read -r full short msg; do
              class="other"
              lower=$(echo "$msg" | tr '[:upper:]' '[:lower:]')
              if echo "$lower" | grep -E -q 'overflow|buffer|use-after-free|memory|sanitize|security'; then
                class="security"; sec_count=$((sec_count+1))
              elif echo "$lower" | grep -E -q 'perf|optimi|speed|fast|cache'; then
                class="perf"; perf_count=$((perf_count+1))
              elif echo "$lower" | grep -E -q 'refactor|cleanup|rename|style'; then
                class="refactor"; ref_count=$((ref_count+1))
              fi
              total=$((total+1))
              echo "<li class=\"$class\">🔗 <a href=\"https://github.com/WebKit/WebKit/commit/$full\" target=\"_blank\">$short</a> — $msg</li>"
            done < ../commits_raw.txt
            echo "</ul>"
            echo "<a href=\"#top\" class=\"back\">⬆ Back to Top</a>"

            # summary
            echo "<h2 id=\"summary\">Summary</h2>"
            echo "<ul>"
            echo "<li>🔴 Security related: $sec_count</li>"
            echo "<li>🟢 Performance: $perf_count</li>"
            echo "<li>🔵 Refactors: $ref_count</li>"
            echo "<li>📦 Total commits: $total</li>"
            echo "</ul>"
            echo "<a href=\"#top\" class=\"back\">⬆ Back to Top</a>"

            # diff analysis
            echo "<h2 id=\"diff\">Diff Analysis</h2><pre>"

            git diff origin/${{ github.event.inputs.from_branch }}..origin/${{ github.event.inputs.to_branch }} \
              -- Source/JavaScriptCore \
                 Source/WebCore \
                 Source/WebKit | \
              sed -e 's/&/\&amp;/g' -e 's/</\&lt;/g' -e 's/>/\&gt;/g' | \
              while read -r line; do
                if echo "$line" | grep -qE 'memcpy|memmove|strcpy|strcat|malloc|free|new|delete'; then
                  echo "<span class=\"danger\">⚠️ $line</span>"
                else
                  echo "$line"
                fi
              done

            echo "</pre>"
            echo "<a href=\"#top\" class=\"back\">⬆ Back to Top</a>"
            echo "</body></html>"
          } > ../filtered_diff.html

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: webkit-diff
          path: filtered_diff.html